updated cli run scripts/ecosystem configs

diff --git a/bin/cli b/bin/cli
--- a/bin/cli
+++ b/bin/cli
@@ -4,19 +4,14 @@
 # ARGBASH_SET_INDENT([  ])
 # DEFINE_SCRIPT_DIR([_script_dir])
 #
-# ARG_OPTIONAL_BOOLEAN([verbose])
 # ARG_OPTIONAL_BOOLEAN([dry-run],[])
 #
 # ARG_OPTIONAL_SINGLE([env],[],[Env Mode; Required],[unspecified])
 # ARG_TYPE_GROUP_SET([envmode],[ENVMODE],[env],[dev,test,prod],[])
+# ARG_LEFTOVERS([])
+# ARG_HELP([RunCLI],[Run a command line app])
 #
-# ARG_OPTIONAL_ACTION([start],[],[Start pm2 with *-ecosystem.config],[pm2_start])
-# ARG_OPTIONAL_ACTION([reset],[],[stop/flush logs/del all],[pm2_reset])
-# ARG_OPTIONAL_ACTION([restart],[],[reset + start],[pm2_restart])
-#
-# ARG_HELP([PM2 Control],[Wrapper around PM2 start/stop/etc.])
-#
-# ARGBASH_PREPARE()
+# ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
 ### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
@@ -61,8 +56,12 @@ begins_with_short_option()
   test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
 
+# THE DEFAULTS INITIALIZATION - POSITIONALS
+# The positional args array has to be reset before the parsing, because it may already be defined
+# - for example if this script is sourced by an argbash-powered script.
+_positionals=()
+_arg_leftovers=()
 # THE DEFAULTS INITIALIZATION - OPTIONALS
-_arg_verbose="off"
 _arg_dry_run="off"
 _arg_env="unspecified"
 
@@ -72,31 +71,24 @@ _arg_env="unspecified"
 # and it makes sense to remind the user how the script is supposed to be called.
 print_help()
 {
-  printf '%s\n' "PM2 Control"
-  printf 'Usage: %s [--(no-)verbose] [--(no-)dry-run] [--env <ENVMODE>] [--start] [--reset] [--restart] [-h|--help]\n' "$0"
+  printf '%s\n' "RunCLI"
+  printf 'Usage: %s [--(no-)dry-run] [--env <ENVMODE>] [-h|--help] ... \n' "$0"
   printf '\t%s\n' "--env: Env Mode; Required. Can be one of: 'dev', 'test' and 'prod' (default: 'unspecified')"
-  printf '\t%s\n' "--start: Start pm2 with *-ecosystem.config"
-  printf '\t%s\n' "--reset: stop/flush logs/del all"
-  printf '\t%s\n' "--restart: reset + start"
   printf '\t%s\n' "-h, --help: Prints help"
-  printf '\n%s\n' "Wrapper around PM2 start/stop/etc."
+  printf '\n%s\n' "Run a command line app"
 }
 
 
 # The parsing of the command-line
 parse_commandline()
 {
+  _positionals_count=0
   while test $# -gt 0
   do
     _key="$1"
     case "$_key" in
-      # The verbose argurment doesn't accept a value,
-      # we expect the --verbose, so we watch for it.
-      --no-verbose|--verbose)
-        _arg_verbose="on"
-        test "${1:0:5}" = "--no-" && _arg_verbose="off"
-        ;;
-      # See the comment of option '--verbose' to see what's going on here - principle is the same.
+      # The dry-run argurment doesn't accept a value,
+      # we expect the --dry-run, so we watch for it.
       --no-dry-run|--dry-run)
         _arg_dry_run="on"
         test "${1:0:5}" = "--no-" && _arg_dry_run="off"
@@ -117,22 +109,7 @@ parse_commandline()
       --env=*)
         _arg_env="$(envmode "${_key##--env=}" "env")" || exit 1
         ;;
-      # See the comment of option '--verbose' to see what's going on here - principle is the same.
-      --start)
-        pm2_start
-        exit 0
-        ;;
-      # See the comment of option '--verbose' to see what's going on here - principle is the same.
-      --reset)
-        pm2_reset
-        exit 0
-        ;;
-      # See the comment of option '--verbose' to see what's going on here - principle is the same.
-      --restart)
-        pm2_restart
-        exit 0
-        ;;
-      # See the comment of option '--verbose' to see what's going on here - principle is the same.
+      # See the comment of option '--dry-run' to see what's going on here - principle is the same.
       -h|--help)
         print_help
         exit 0
@@ -146,15 +123,46 @@ parse_commandline()
         exit 0
         ;;
       *)
-        _PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
+        _last_positional="$1"
+        _positionals+=("$_last_positional")
+        _positionals_count=$((_positionals_count + 1))
         ;;
     esac
     shift
   done
 }
 
-# Call the function that assigns passed optional arguments to variables:
-#  parse_commandline "$@"
+
+# Take arguments that we have received, and save them in variables of given names.
+# The 'eval' command is needed as the name of target variable is saved into another variable.
+assign_positional_args()
+{
+  local _positional_name _shift_for=$1
+  # We have an array of variables to which we want to save positional args values.
+  # This array is able to hold array elements as targets.
+  # As variables don't contain spaces, they may be held in space-separated string.
+  _positional_names=""
+  # If we allow up to infinitely many args, we calculate how many of values
+  # were actually passed, and we extend the target array accordingly.
+  # We also know that we have _pos_names_count known positional arguments.
+  _our_args=$((${#_positionals[@]} - 0))
+  for ((ii = 0; ii < _our_args; ii++))
+  do
+    _positional_names="$_positional_names _arg_leftovers[$((ii + 0))]"
+  done
+
+  shift "$_shift_for"
+  for _positional_name in ${_positional_names}
+  do
+    test $# -gt 0 || break
+    eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
+    shift
+  done
+}
+
+# Now call all the functions defined above that are needed to get the job done
+parse_commandline "$@"
+assign_positional_args 1 "${_positionals[@]}"
 
 # OTHER STUFF GENERATED BY Argbash
 _script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || { echo "Couldn't determine the script's running directory, which probably matters, bailing out" >&2; exit 2; }
@@ -165,41 +173,12 @@ _script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || { echo "Couldn't 
 # [ <-- needed because of Argbash
 #
 readonly script_dir="$_script_dir"
-
 source "$script_dir/_utils.sh"
 
-pm2_start() {
-    arg env
-    with_dirs 'packages/services'
-    readonly ecosystem_config="./dist/src/pm2/${env}-ecosystem.config.js"
-    test -f "$ecosystem_config" || die "pm2 config $ecosystem_config does not exist"
-    doit pm2 start $ecosystem_config --env="$env"
-    doit pm2 logs
-}
+readonly climain="./packages/services/dist/src/cli"
+arg env
 
-pm2_reset() {
-    doit pm2 stop all
-    doit pm2 flush
-    doit pm2 delete all
-}
-
-pm2_restart() {
-    pm2_reset
-    pm2_start
-}
-
-
-# --logs [service]
-#  pm2 logs --nostream  --lines 100000
-#  pm2 logs
-#  pm2 status
-
-#########################
-## Run Main
-#########################
-parse_commandline "$@"
-
-## Print help if no other action has been taken
-_PRINT_HELP=yes die "" 1
+export NODE_ENV="$env"
+doit node "$climain" "${_arg_leftovers[@]}"
 
 # ] <-- needed because of Argbash
