pm2 control bash scripts

diff --git a/bin/pm2-control b/bin/pm2-control
--- a/bin/pm2-control
+++ b/bin/pm2-control
@@ -1,14 +1,21 @@
 #!/bin/bash
+#############################
 # shellcheck disable=2154
-
-# Created by argbash-init v2.10.0
-# DEFINE_SCRIPT_DIR([_script_dir])
-# ARG_OPTIONAL_ACTION([rebuild-script],[],[Rebuild this script (requires argbash installed)],[do_rebuild_script])
-# ARG_OPTIONAL_ACTION([reset],[],[stop/flush logs/del all],[pm2_reset])
-# ARG_OPTIONAL_BOOLEAN([verbose])
-# ARG_OPTIONAL_BOOLEAN([dry-run])
-# ARG_HELP([PM2 Control],[Wrapper around PM2 start/stop/etc.])
+#
 # ARGBASH_SET_INDENT([  ])
+# DEFINE_SCRIPT_DIR([_script_dir])
+#
+# ARG_OPTIONAL_BOOLEAN([verbose])
+# ARG_OPTIONAL_BOOLEAN([dry-run],[])
+# ARG_OPTIONAL_SINGLE([env],[],[Env Mode],[unspecified])
+# ARG_TYPE_GROUP_SET([envmode],[ENVMODE],[env],[dev,test,prod],[])
+# ARG_HELP([PM2 Control],[Wrapper around PM2 start/stop/etc.])
+#
+# ARG_OPTIONAL_ACTION([rebuild-script],[],[Rebuild this script (requires argbash installed)],[do_rebuild_script])
+# ARG_OPTIONAL_ACTION([start],[],[Start pm2 with *-ecosystem.config],[pm2_start])
+# ARG_OPTIONAL_ACTION([reset],[],[stop/flush logs/del all],[pm2_reset])
+# ARG_OPTIONAL_ACTION([restart],[],[reset + start],[pm2_restart])
+#
 # ARGBASH_PREPARE()
 # needed because of Argbash --> m4_ignore([
 ### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
@@ -31,6 +38,18 @@ die()
   exit "${_ret}"
 }
 
+# validators
+
+envmode()
+{
+  local _allowed=("dev" "test" "prod") _seeking="$1"
+  for element in "${_allowed[@]}"
+  do
+    test "$element" = "$_seeking" && echo "$element" && return 0
+  done
+  die "Value '$_seeking' (of argument '$2') doesn't match the list of allowed values: 'dev', 'test' and 'prod'" 4
+}
+
 
 # Function that evaluates whether a value passed to it begins by a character
 # that is a short option of an argument the script knows about.
@@ -45,6 +64,7 @@ begins_with_short_option()
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 _arg_verbose="off"
 _arg_dry_run="off"
+_arg_env="unspecified"
 
 
 # Function that prints general usage of the script.
@@ -53,10 +73,13 @@ _arg_dry_run="off"
 print_help()
 {
   printf '%s\n' "PM2 Control"
-  printf 'Usage: %s [--rebuild-script] [--reset] [--(no-)verbose] [--(no-)dry-run] [-h|--help]\n' "$0"
-  printf '\t%s\n' "--rebuild-script: Rebuild this script (requires argbash installed)"
-  printf '\t%s\n' "--reset: stop/flush logs/del all"
+  printf 'Usage: %s [--(no-)verbose] [--(no-)dry-run] [--env <ENVMODE>] [-h|--help] [--rebuild-script] [--start] [--reset] [--restart]\n' "$0"
+  printf '\t%s\n' "--env: Env Mode. Can be one of: 'dev', 'test' and 'prod' (default: 'unspecified')"
   printf '\t%s\n' "-h, --help: Prints help"
+  printf '\t%s\n' "--rebuild-script: Rebuild this script (requires argbash installed)"
+  printf '\t%s\n' "--start: Start pm2 with *-ecosystem.config"
+  printf '\t%s\n' "--reset: stop/flush logs/del all"
+  printf '\t%s\n' "--restart: reset + start"
   printf '\n%s\n' "Wrapper around PM2 start/stop/etc."
 }
 
@@ -68,28 +91,34 @@ parse_commandline()
   do
     _key="$1"
     case "$_key" in
-      # The rebuild-script argurment doesn't accept a value,
-      # we expect the --rebuild-script, so we watch for it.
-      --rebuild-script)
-        do_rebuild_script
-        exit 0
-        ;;
-      # See the comment of option '--rebuild-script' to see what's going on here - principle is the same.
-      --reset)
-        pm2_reset
-        exit 0
-        ;;
-      # See the comment of option '--rebuild-script' to see what's going on here - principle is the same.
+      # The verbose argurment doesn't accept a value,
+      # we expect the --verbose, so we watch for it.
       --no-verbose|--verbose)
         _arg_verbose="on"
         test "${1:0:5}" = "--no-" && _arg_verbose="off"
         ;;
-      # See the comment of option '--rebuild-script' to see what's going on here - principle is the same.
+      # See the comment of option '--verbose' to see what's going on here - principle is the same.
       --no-dry-run|--dry-run)
         _arg_dry_run="on"
         test "${1:0:5}" = "--no-" && _arg_dry_run="off"
         ;;
-      # See the comment of option '--rebuild-script' to see what's going on here - principle is the same.
+      # We support whitespace as a delimiter between option argument and its value.
+      # Therefore, we expect the --env value, so we watch for --env.
+      # Since we know that we got the long option,
+      # we just reach out for the next argument to get the value.
+      --env)
+        test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
+        _arg_env="$(envmode "$2" "env")" || exit 1
+        shift
+        ;;
+      # We support the = as a delimiter between option argument and its value.
+      # Therefore, we expect --env=value, so we watch for --env=*
+      # For whatever we get, we strip '--env=' using the ${var##--env=} notation
+      # to get the argument value
+      --env=*)
+        _arg_env="$(envmode "${_key##--env=}" "env")" || exit 1
+        ;;
+      # See the comment of option '--verbose' to see what's going on here - principle is the same.
       -h|--help)
         print_help
         exit 0
@@ -100,6 +129,26 @@ parse_commandline()
       # that the first character that follows coresponds to a short option.
       -h*)
         print_help
+        exit 0
+        ;;
+      # See the comment of option '--verbose' to see what's going on here - principle is the same.
+      --rebuild-script)
+        do_rebuild_script
+        exit 0
+        ;;
+      # See the comment of option '--verbose' to see what's going on here - principle is the same.
+      --start)
+        pm2_start
+        exit 0
+        ;;
+      # See the comment of option '--verbose' to see what's going on here - principle is the same.
+      --reset)
+        pm2_reset
+        exit 0
+        ;;
+      # See the comment of option '--verbose' to see what's going on here - principle is the same.
+      --restart)
+        pm2_restart
         exit 0
         ;;
       *)
@@ -115,26 +164,45 @@ parse_commandline()
 
 # OTHER STUFF GENERATED BY Argbash
 _script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || { echo "Couldn't determine the script's running directory, which probably matters, bailing out" >&2; exit 2; }
+# Validation of values
+
 
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
+#
 
 
 # shopt -s extglob
 # set -euo pipefail
 
-script_basename=$(basename "$0")
-
-## Assign parsed args to prettier variables
 readonly script_dir=$_script_dir
-readonly dryrun=$_arg_dry_run
-readonly verbose=$_arg_verbose
+
+
+arg() {
+    local argname="${1:-unspecified}"
+    test "$argname" == "unspecified" && die "Error: no argument name passed to arg()"
+
+    local argloc="_arg_$argname"
+    test -z ${!argloc+x} && die "Error: arg $argname (expected in \$$argloc) is unset"
+
+    local argval=${!argloc}
+
+    # echo "arg $argname (expected in \$$argloc) = $argval"
+
+    ## 'return' the value of the parsed argument in the passed in string
+    eval "$argname"="$argval"
+}
 
 ####
 ## Run the given command, allowing for --dry-run option to just print the command
 doit() {
+    arg dry_run
+    arg env
+    test "$env" == "unspecified" && _PRINT_HELP=yes die "Error: must specify --env=..."
+    export NODE_ENV="$env"
+
     local cmds=("$@")
-    if [ "$dryrun" = on ]; then
+    if [ "$dry_run" = on ]; then
         echo "dry> ${cmds[*]}"
     else
         echo "run> ${cmds[*]}"
@@ -156,18 +224,26 @@ with_dirs() {
         fi
         cd "$d" || exit 1
     done
-    echo "In dir: $(pwd)"
+    echo "pwd> $(pwd)"
 }
 
 ####
 ## Convenience function to regenerate this script from argbash source (*.m4)
 do_rebuild_script() {
     echo "Rebuilding script.."
+    script_basename=$(basename "$0")
     with_dirs "$script_dir"
     argbash "$script_basename.m4" -c -o "$script_basename"
 }
 
-
+#  pm2 start dist/src/pm2/service-ecosystem.config.js --env=dev && pm2 logs
+pm2_start() {
+    arg env
+    with_dirs 'packages/services'
+    readonly ecosystem_config='./dist/src/pm2/service-ecosystem.config.js'
+    doit pm2 start $ecosystem_config --env="$env"
+    doit pm2 logs
+}
 
 pm2_reset() {
     doit pm2 stop all
@@ -175,13 +251,10 @@ pm2_reset() {
     doit pm2 delete all
 }
 
-# --reset
-#  pm2 stop all && pm2 flush && pm2 del all
-
-# --start
-#  pm2 start dist/src/pm2/service-ecosystem.config.js --env=dev && pm2 logs
-
-# --fresh-start = --reset + --start
+pm2_restart() {
+    pm2_reset
+    pm2_start
+}
 
 
 # --logs [service]
@@ -203,6 +276,8 @@ pm2_reset() {
 ## Run Main
 #########################
 parse_commandline "$@"
+
+run_deferred
 
 ## Print help if no other action has been taken
 _PRINT_HELP=yes die "" 1
